### ISSUE TITLE
TaglessJSS mixin to cause an error on destroying component .

### ISSUE THREAD

**Issue by alexeiruckiy** [exeto/ember-cli-jss#107]
TaglessJSS doesn't have any sort of dom id. So when it calls detach method of stylesheet object with empty id it causes an error.

**Comment by alexeiruckiy** [comment]
When component is destroyed He calls stylesheet object method detach method with elementId. Tagless component doesn't have any sort of dom id.

**Comment by exeto** [comment]
`v2.1.1`
